kind: Namespace
apiVersion: v1
metadata:
  name: gitreleases
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gitreleases-{{TAG}}
  namespace: gitreleases
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gitreleases
        version: {{TAG}}
      annotations:
        ad.datadoghq.com/gitreleases.check_names: '["gitreleases"]'
        ad.datadoghq.com/gitreleases.init_configs: '[{}]'
        ad.datadoghq.com/gitreleases.instances: '[{"prometheus_url": "http://%%env_METRICS_USERNAME%%:%%env_METRICS_PASSWORD%%@%%host%%:8080/metrics","namespace": "gitreleases","metrics": ["api_requests_*","go_*","in_flight_requests","process_*","promhttp_*","request_duration_*","response_size_*"]}]'
    spec:
      imagePullSecrets:
        - name: gitlab-auth
      containers:
        - name: gitreleases
          image: registry.gitlab.com/mweibel/gitreleases:{{TAG}}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 30
          env:
            - name: LISTEN_ADDR
              value: ":8080"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitreleases-secret
                  key: githubToken
            - name: METRICS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gitreleases-secret
                  key: metricsUsername
            - name: METRICS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitreleases-secret
                  key: metricsPassword
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: gitreleases
    version: {{TAG}}
  name: gitreleases
  namespace: gitreleases
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: gitreleases
    version: {{TAG}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitreleases
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
  namespace: gitreleases
spec:
  tls:
    - hosts:
      - gitreleases.dev
      secretName: gitreleases-tls
  rules:
    - host: gitreleases.dev
      http:
        paths:
          - backend:
              serviceName: gitreleases
              servicePort: http
