kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gitreleases-{{TAG}}
  namespace: gitreleases
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gitreleases
        version: {{TAG}}
      annotations:
        ad.datadoghq.com/gitreleases.check_names: '["prometheus"]'
        ad.datadoghq.com/gitreleases.init_configs: '[{}]'
        ad.datadoghq.com/gitreleases.instances: '[{"prometheus_url": "http://%%env_METRICS_USERNAME%%:%%env_METRICS_PASSWORD%%@%%host%%:%%port%%/metrics","namespace": "gitreleases","metrics": ["api_requests_*","go_*","in_flight_requests","process_*","promhttp_*","request_duration_*","response_size_*"]}]'
    spec:
      imagePullSecrets:
        - name: gitlab-auth
      containers:
        - name: gitreleases
          image: registry.gitlab.com/mweibel/gitreleases:{{TAG}}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 30
          env:
            - name: LISTEN_ADDR
              value: ":8080"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitreleases-secret
                  key: githubToken
            - name: METRICS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gitreleases-secret
                  key: metricsUsername
            - name: METRICS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitreleases-secret
                  key: metricsPassword
