apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitreleases
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
  namespace: gitreleases
spec:
  tls:
    - hosts:
        - gitreleases.dev
      secretName: gitreleases-tls
  rules:
    - host: gitreleases.dev
      http:
        paths:
          - backend:
              serviceName: gitreleases
              servicePort: http
